services:
  - type: web
    name: whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: node whatsapp_bot.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: WHATSAPP_PHONE
        sync: false
